### A Pluto.jl notebook ###
# v0.20.17

using Markdown
using InteractiveUtils

# ╔═╡ c87e563e-e6e9-430b-b36e-9b1eaa089b99

md"""
# Compute and compare different radial potentials
"""

# ╔═╡ 1a977b0e-1c1b-408e-ba33-3aed33cf74cf

md"""

We shall here describe how different atomic (radial) potentials can be calculated and applied within the JenaAtomicCalculator toolbox.

Any (radial) potential is handled in JenaAtomicCalculator by the data struct `Radial.Potential` that (may) contain a name, the radial function $Z(r)$ as well as the radial radial_grid on which the potential is defined. The potential function `Zr` typically contains the effective charge $Z(r)$ as seen by an electron, so that the full radial potential is given by $V = -\:Z(r) / r$. This convention has been frequently applied in atomic physics and has also been adopted in JenaAtomicCalculator.

"""

# ╔═╡ 25fdbc3f-13d5-450c-8a0c-8178a6182415

? Radial.Potential

# ╔═╡ 1f216a7a-5a7d-4583-ba2b-21eb311ef678

md"""

Perhaps, the simplest choice of a radial potential is the **nuclear** potential which, of course, depends on the nuclear model. Let us first simply consider a $\;^{12}$C $\;$ carbon atom with a Fermi-distributed nuclear charge and a standard radial radial_grid.

"""

# ╔═╡ d45495d5-1c16-4527-bbaf-3ec8b04f2d7e

begin
radial_grid     = Radial.Grid(true)
nucModel = Nuclear.Model(6., "Fermi")
end

# ╔═╡ 8bfe1059-c378-4abe-af2c-c3b910587629

md"""

Then, the corresponding nuclear potential is generated by simply calling:

"""

# ╔═╡ b709fa6c-3be7-414d-b272-a0faaebc5dcf

nucPotential = Nuclear.nuclearPotential(nucModel, radial_grid)

# ╔═╡ 0504fa35-df4e-4d18-a851-30c1bc51e55c

md"""

As seen from the output, the effective charge Z(r) vanishes near to the origin but quickly increases to the full charge $Z = 6.\;$ at larger $r$-values, i.e. near to the surface and outside of the nucleus

To calculate **atomic** potentials, we also need to know the electron density around the nucleus. Most often, this density refers to a particular atomic level. Therefore, we first need to compute some of the low-lying levels of, for instance, neutral carbon. We shall here just compute the levels of the $1s^2 2s^2 2p^2$ ground-state configuration. We use the *simplest* approximation for these computation but will explain in some later tutorials how we could control and refine such simple structure calculations, if needed.

"""

# ╔═╡ 0cc196c8-be62-49b2-b015-fee7de7a009b

begin
basis     = Basics.performSCF([Configuration("1s^2 2s^2 2p^2")], nucModel, radial_grid, AsfSettings())
multiplet = Basics.performCI(basis, nucModel, radial_grid, AsfSettings());
end

# ╔═╡ 310ac439-3211-4b13-b28b-8afae5687683

md"""

From this multiplet, we just take the *lowest* level (the ground level) in order to calculate the density for the (electronic) potential. In JenaAtomicCalculator, we have different choices for generating such an **electronic** potential that just arise from the electronic density, and as seen from ? compute at the REPL:

   •    ("radial potential: core-Hartree", radial_grid::Radial.Grid, level::Level) 
       ... to compute a (radial) core-Hartree potential for the given level; 
           cf. Basics.computePotentialCoreHartree. A potential::RadialPotential 
           is returned. 

   •    ("radial potential: Kohn-Sham", radial_grid::Radial.Grid, level::Level) 
       ... to compute a (radial) Kohn-Sham potential for the given level; 
           cf. Basics.computePotentialKohnSham. A potential::RadialPotential is 
           returned.

   •    ("radial potential: Dirac-Fock-Slater", radial_grid::Radial..Grid, level::Level) 
       ... to compute a (radial) Dirac-Fock-Slater potential for the given level; this 
           potential is rather simple but includes some undesired self-interaction and 
           exhibits a wrong asymptotic behaviour. Cf. Basics.computePotentialDFS. 
           A potential::RadialPotential is returned.

"""

# ╔═╡ 8a3b3a24-ec2b-4c5a-b9ee-bb028dfaf7a6

begin
level  = multiplet.levels[1]
potCH  = compute("radial potential: core-Hartree", radial_grid, level)
potDFS = compute("radial potential: Dirac-Fock-Slater", radial_grid, level)
potKS = compute("radial potential: Kohn-Sham", radial_grid, level)
end

# ╔═╡ f7b8b729-49f7-4512-b3cb-9b7888cab3c0

md"""

All these potentials are represented as *effective charge* $Z(r)$ and can be added to the nuclear potential, for example:
"""

# ╔═╡ 00424e40-6681-4740-a0b7-6c40b8273f9c

atomPotDFS = add(nucPotential, potDFS)

# ╔═╡ 097c63cb-2d59-4462-8619-74c370e37f8b

md"""

As seen from this output, the effective charge of the overall atomic potential goes to *zero* as required for a neutral atom. We can display these potentials also graphically by using `JenaAtomicCalculator.plot()`
"""

# ╔═╡ 3c11b594-404e-4748-9ed2-81400b8b71bc

begin
nucPotential2 = Nuclear.nuclearPotential(Model(6.,"uniform"), radial_grid)
nucPotential3 = Nuclear.nuclearPotential(Model(6., "point"), radial_grid)
atomPotCH = add(nucPotential2, potCH)
atomPotKS = add(nucPotential3, potKS)
plot("radial potentials", [atomPotDFS,atomPotCH, atomPotKS], radial_grid;N=300)
end

# ╔═╡ 1642762b-dbeb-44c9-938b-e95f9d3e50b4

md"""
It is directly noticeable, that the functions based on the Kohn-Sham and Dirac-Fock-Slater potential correspond to the expectation for a neutral atom since the curve for large r approaches 0. In contrast, the curve for the Core-Hartree potential converges to a value greater than 0. That is due to the fact that the summation for the Core-Hartree potential runs only over all core orbitals as it is mainly applied for atoms with a single valence electron (alkali atoms). The graph thus shows the effective charge a single valence electron would "see". To illustrate the different nuclear potentials, we could also look at the functions at a closer angle, simply by choosing a smaller N (number of radial_grid points to be considered).
"""

# ╔═╡ e26fa949-c192-4039-a13a-edc465f05417

plot("radial potentials", [atomPotDFS,atomPotCH, atomPotKS], radial_grid;N=75)

# ╔═╡ a66d097c-d342-4e3e-9818-0a0da2ec13e7

md"""
The plot shows very well the caracteristics of the different nuclear models implemented in JenaAtomicCalculator.
"""


# ╔═╡ 6e92b6f6-8ddb-44f1-8236-2063fcd54433

begin
using Plots
using JenaAtomicCalculator
end

# ╔═╡ 1c91feff-a55d-404f-9c93-5e57aa8562f3

begin
    using JenaAtomicCalculator
    using Plots
end

# ╔═╡ Cell order:
# ╠═1c91feff-a55d-404f-9c93-5e57aa8562f3
# ╠═c87e563e-e6e9-430b-b36e-9b1eaa089b99
# ╠═6e92b6f6-8ddb-44f1-8236-2063fcd54433
# ╠═1a977b0e-1c1b-408e-ba33-3aed33cf74cf
# ╠═25fdbc3f-13d5-450c-8a0c-8178a6182415
# ╠═1f216a7a-5a7d-4583-ba2b-21eb311ef678
# ╠═d45495d5-1c16-4527-bbaf-3ec8b04f2d7e
# ╠═8bfe1059-c378-4abe-af2c-c3b910587629
# ╠═b709fa6c-3be7-414d-b272-a0faaebc5dcf
# ╠═0504fa35-df4e-4d18-a851-30c1bc51e55c
# ╠═0cc196c8-be62-49b2-b015-fee7de7a009b
# ╠═310ac439-3211-4b13-b28b-8afae5687683
# ╠═8a3b3a24-ec2b-4c5a-b9ee-bb028dfaf7a6
# ╠═f7b8b729-49f7-4512-b3cb-9b7888cab3c0
# ╠═00424e40-6681-4740-a0b7-6c40b8273f9c
# ╠═097c63cb-2d59-4462-8619-74c370e37f8b
# ╠═3c11b594-404e-4748-9ed2-81400b8b71bc
# ╠═1642762b-dbeb-44c9-938b-e95f9d3e50b4
# ╠═e26fa949-c192-4039-a13a-edc465f05417
# ╠═a66d097c-d342-4e3e-9818-0a0da2ec13e7
